[deps]
Augmentor = "02898b10-1f73-11ea-317c-6393d7073e15"
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
Comonicon = "863f3e99-da2a-4334-8734-de3dacbe5542"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
LuxAMDGPU = "83120cb1-ca15-4f04-bf3b-6967d2e6b60b"
LuxCUDA = "d0bbae9a-e099-4d5b-a835-1c6931763bda"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Augmentor = "0.6"
BSON = "0.3"
Comonicon = "1"
Images = "0.24, 0.25"
Lux = "0.4"
LuxAMDGPU = "0.1"
LuxCUDA = "0.2, 0.3"
MLUtils = "0.3, 0.4"
Optimisers = "0.2"
Plots = "1"
ProgressBars = "1"
Setfield = "1"
Zygote = "0.6"
julia = "1.6"
