[deps]
AMDGPU = "21141c5a-9bdb-4563-92ae-f87d6854732e"
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
Comonicon = "863f3e99-da2a-4334-8734-de3dacbe5542"
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
DataAugmentation = "88a5189c-e7ff-4f85-ac6b-e6158070f02e"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
LuxCUDA = "d0bbae9a-e099-4d5b-a835-1c6931763bda"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
ParameterSchedulers = "d7d3b36b-41b8-4d0d-a2bf-768c6151755e"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TensorBoardLogger = "899adc3e-224a-11e9-021f-63837185c80f"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
AMDGPU = "0.8.4, 0.9, 1"
ArgCheck = "2.3.0"
CairoMakie = "0.12"
ChainRulesCore = "1.23"
Comonicon = "1"
ConcreteStructs = "0.2.3"
DataAugmentation = "0.2.12"
DataDeps = "0.7.13"
FileIO = "1.16"
ImageCore = "0.9, 0.10"
ImageIO = "0.6"
JLD2 = "0.4.48"
Lux = "0.5.52"
LuxCUDA = "0.3"
MLUtils = "0.4"
Optimisers = " 0.3"
ParameterSchedulers = "0.4.1"
ProgressBars = "1"
Random = "1.10"
Setfield = "1"
StableRNGs = "1.0.2"
Statistics = "1.10"
TensorBoardLogger = "0.1"
Zygote = "0.6"

[extras]
CUDA_Runtime_jll = "76a88914-d11a-5bdc-97e0-2f5a05c973a2"
