[deps]
Boltz = "4544d5e4-abc5-4dea-817f-29e4c205d9c8"
DataAugmentation = "88a5189c-e7ff-4f85-ac6b-e6158070f02e"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Format = "1fa38f19-a742-5d3f-a2b9-30dd87b9d5f8"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
MLDataDevices = "7e8f7934-dd98-4c1a-8fe8-92b47a384d40"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
OneHotArrays = "0b1bfda6-eb8a-41d2-88d8-f5af5cad476f"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
ParameterSchedulers = "d7d3b36b-41b8-4d0d-a2bf-768c6151755e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[sources]
Lux = {path = "../.."}

[compat]
Boltz = "1"
DataAugmentation = "0.3"
Dates = "1.10"
FileIO = "1.16"
Format = "1.3"
ImageIO = "0.6"
ImageMagick = "1"
JLD2 = "0.5.1, 0.6"
Lux = "1"
MLDataDevices = "1.17"
OneHotArrays = "0.2.5"
Optimisers = "0.4.6"
ParameterSchedulers = "0.4.2"
Random = "1.10"
Setfield = "1.1.1"
Zygote = "0.7"
