name = "Lux"
uuid = "b2108857-7c20-44ae-9111-449ecde12c47"
authors = ["Avik Pal <avikpal@mit.edu> and contributors"]
version = "1.29.3"

[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ArrayInterface = "4fba245c-0d91-5ea0-9b3e-6abc04ee57a9"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
DispatchDoctor = "8d63f2c5-f18a-4cf2-ba9d-b3f60fc568c8"
EnzymeCore = "f151be2c-9106-41f4-ab19-57ee4f262869"
FastClosures = "9aa1b823-49e4-5ca5-8b0f-3971ec8bab6a"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LuxCore = "bb33d45b-7691-41d6-9220-0943567d0623"
LuxLib = "82251201-b29d-42c6-8e01-566dec8acb11"
MLDataDevices = "7e8f7934-dd98-4c1a-8fe8-92b47a384d40"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReactantCore = "a3311ec8-5e00-46d5-b541-4f83e724a433"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SciMLPublic = "431bcebd-1456-4ced-9d72-93c2757fff0b"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"
StaticArraysCore = "1e83bf80-4336-4d27-bf5d-d5a4f845583c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
WeightInitializers = "d49dbf32-c5c2-4618-8acc-27bb2598ef2d"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
LossFunctions = "30fc2ffe-d236-52d8-8643-a9d8f7c094a7"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
NCCL = "3fe64909-d7a1-4096-9b7d-7a0f12cf0f6b"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
SimpleChains = "de6bee2f-e2f4-4ec7-b6ed-219cc6f6e9e5"
Tracker = "9f7883ad-71c0-57eb-9f7f-b5c9e6d3789c"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[sources]
LuxCore = { path = "lib/LuxCore" }
LuxLib = { path = "lib/LuxLib" }
MLDataDevices = { path = "lib/MLDataDevices" }
WeightInitializers = { path = "lib/WeightInitializers" }

[extensions]
ComponentArraysExt = "ComponentArrays"
EnzymeExt = "Enzyme"
FluxExt = "Flux"
GPUArraysExt = "GPUArrays"
LossFunctionsExt = "LossFunctions"
MLUtilsExt = "MLUtils"
MPIExt = "MPI"
MPINCCLExt = ["CUDA", "MPI", "NCCL"]
MooncakeExt = "Mooncake"
ReactantExt = [
    "Enzyme",
    "Reactant",
    "Functors",
    "ReactantCore",
    "LuxLib",
    "MLDataDevices",
    "Optimisers",
    "NNlib",
    "Statistics",
]
ReverseDiffExt = ["FunctionWrappers", "ReverseDiff"]
SimpleChainsExt = "SimpleChains"
TrackerExt = "Tracker"
ZygoteExt = "Zygote"

[compat]
ADTypes = "1.15"
Adapt = "4.1"
ArrayInterface = "7.17.1"
CUDA = "5.8"
ChainRulesCore = "1.25.1"
ComponentArrays = "0.15.28"
ConcreteStructs = "0.2.3"
DiffResults = "1.1"
DispatchDoctor = "0.4.26"
Enzyme = "0.13.81"
EnzymeCore = "0.8.15"
FastClosures = "0.3.2"
Flux = "0.16.3"
ForwardDiff = "0.10.36, 1"
FunctionWrappers = "1.1.3"
Functors = "0.5"
GPUArrays = "11"
GPUArraysCore = "0.2"
LinearAlgebra = "1.10"
LossFunctions = "0.11.1, 1"
LuxCore = "1.5.1"
LuxLib = "1.15"
MLDataDevices = "1.17"
MLUtils = "0.4.4"
MPI = "0.20.19"
MacroTools = "0.5.13"
Markdown = "1.10"
Mooncake = "0.4.148"
NCCL = "0.1.2"
NNlib = "0.9.27"
Optimisers = "0.4.6"
PrecompileTools = "1.2.1"
Preferences = "1.4.3"
Random = "1.10"
Reactant = "0.2.190"
ReactantCore = "0.1.16"
Reexport = "1.2.2"
ReverseDiff = "1.15"
SciMLPublic = "1.0.0"
Setfield = "1.1.1"
SimpleChains = "0.4.7"
Static = "1.1.1"
StaticArraysCore = "1.4.3"
Statistics = "1.10"
Tracker = "0.2.37"
UUIDs = "1.10"
WeightInitializers = "1.3"
Zygote = "0.7"
julia = "1.10"

[workspaces]
projects = ["test", "docs"]
