[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DynamicExpressions = "a40a106e-89c9-4ca8-8020-a735e8728b6b"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
Latexify = "23fbe1c1-3f47-55db-b15f-69d7ec21a316"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
OptimizationOptimisers = "42dfb2eb-d2b4-4451-abcd-913932933ac1"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
SymbolicRegression = "8254be44-1295-4e6a-a16d-46603ac705cb"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"

[compat]
CairoMakie = "0.12"
ComponentArrays = "0.15.11"
DynamicExpressions = "0.16.0, 0.17"
Latexify = "0.16.2"
Literate = "2"
Lux = "0.5"
MLJ = "0.20.3"
Optimization = "3.24.3"
OptimizationOptimJL = "0.2.3, 0.3"
OptimizationOptimisers = "0.2.1"
OrdinaryDiffEq = "6.74.1"
SciMLSensitivity = "7.57"
Statistics = "1.11"
SymbolicRegression = "0.24.1"
SymbolicUtils = "1.5.1, 2"
