[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CairoMakie = "0.13.1"
ConcreteStructs = "0.2.3"
Enzyme = "0.13.28"
Lux = "1.5"
MLUtils = "0.4.5"
Optimisers = "0.4.4"
Printf = "1.10"
Random = "1.10"
Reactant = "0.2.21"
Statistics = "1.10"
