[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
DataAugmentation = "88a5189c-e7ff-4f85-ac6b-e6158070f02e"
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
ImageShow = "4e3cecfd-b093-5904-9786-8bbb286a6a31"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
OhMyThreads = "67456a42-1dca-4109-a031-0a68de7e3ad5"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
ParameterSchedulers = "d7d3b36b-41b8-4d0d-a2bf-768c6151755e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressTables = "e0b4b9f6-8cc7-451e-9c86-94c5316e9f73"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TensorBoardLogger = "899adc3e-224a-11e9-021f-63837185c80f"

[compat]
ArgParse = "1"
ConcreteStructs = "0.2.3"
DataAugmentation = "0.3"
DataDeps = "0.7.13"
Enzyme = "0.13.27"
FileIO = "1.16"
ImageCore = "0.9, 0.10"
ImageIO = "0.6"
ImageShow = "0.3"
JLD2 = "0.4.48, 0.5, 0.6"
Lux = "1"
MLUtils = "0.4"
OhMyThreads = "0.8"
Optimisers = "0.4.6"
ParameterSchedulers = "0.4.1"
Printf = "1.10"
ProgressTables = "0.1.0"
Random = "1.10"
Reactant = "0.2.175"
StableRNGs = "1.0.2"
Statistics = "1.10"
TensorBoardLogger = "0.1"
