[deps]
AbstractDifferentiation = "c29ec348-61ec-40c8-8164-b8c60e9d9f3d"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DataLoaders = "2e981812-ef13-4a9c-bfa0-ab13047b12a9"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
MakiePublication = "dde8697e-0d61-460d-88dd-856f66710dd1"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
OneHotArrays = "0b1bfda6-eb8a-41d2-88d8-f5af5cad476f"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReverseDiff = "37e2e3b7-166d-5795-8a7a-e32c996b4267"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
AbstractDifferentiation = "0.4, 0.5"
CUDA = "3, 4"
CairoMakie = "0.9, 0.10"
ComponentArrays = "0.13"
DataLoaders = "0.1"
ForwardDiff = "0.10"
Functors = "0.2, 0.3, 0.4"
Lux = "0.4"
MLDatasets = "0.5, 0.7"
MLUtils = "0.2, 0.3, 0.4"
MakiePublication = "0.3"
NNlib = "0.8"
OneHotArrays = "0.1, 0.2"
Optimisers = "0.2"
OrdinaryDiffEq = "6"
ReverseDiff = "1"
SciMLSensitivity = "7"
Setfield = "0.8, 1"
Turing = "0.21, 0.22, 0.23, 0.24"
Zygote = "0.6"
