[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"

[compat]
CairoMakie = "0.13.6, 0.14, 0.15"
Enzyme = "0.13.81"
Lux = "1.12.4"
MLUtils = "0.4.8"
Optimisers = "0.4.6"
Random = "1.10"
Reactant = "0.2.170"
