[deps]
BFloat16s = "ab4f0b2a-ad5b-11e8-123f-65d77653426b"
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
HuggingFaceTokenizers = "a6888d44-1185-43bb-bd0f-7806f9976d18"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"
SafeTensors = "eeda0dda-7046-4914-a807-2495fc7abb89"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
BFloat16s = "0.5, 0.6"
ConcreteStructs = "0.2"
HuggingFaceTokenizers = "0.1"
JSON3 = "1.14"
LinearAlgebra = "1.10"
Lux = "1.20"
PythonCall = "0.9.27"
Random = "1.10"
Reactant = "0.2.170"
SafeTensors = "1.2"
Scratch = "1.3"
Statistics = "1.10"
