[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
MakiePublication = "dde8697e-0d61-460d-88dd-856f66710dd1"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Tracker = "9f7883ad-71c0-57eb-9f7f-b5c9e6d3789c"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"

[compat]
CairoMakie = "0.9, 0.10, 0.11"
Functors = "0.2, 0.3, 0.4"
LinearAlgebra = "1"
Lux = "0.5"
MakiePublication = "0.3"
Random = "1"
Tracker = "0.2"
Turing = "0.30"
