[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationOptimJL = "36348300-93cb-4f02-beb5-3c3902f8871e"
OrdinaryDiffEqLowOrderRK = "1344f307-1e59-4825-a18e-ace9aa3fa4c6"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SciMLSensitivity = "1ed8b502-d754-442c-8d5d-10ac956f44a1"

[compat]
CairoMakie = "0.12, 0.13"
ComponentArrays = "0.15.22"
LineSearches = "7"
Lux = "1"
Optimization = "4"
OptimizationOptimJL = "0.4"
OrdinaryDiffEqLowOrderRK = "1"
SciMLSensitivity = "7.57"
