theme:
  name: material
  features:
    - header.autohide # header disappears as you scroll
    - navigation.top
  palette:
    # Light mode / dark mode
    # We deliberately don't automatically use `media` to check a user's preferences. We default to light mode as
    # (a) it looks more professional, and (b) is more obvious about the fact that it offers a (dark mode) toggle.
    - scheme: default
      primary: white
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Lato
  icon:
    repo: fontawesome/brands/github # GitHub logo in top right
    # logo: "material/circle-opacity" # Equinox logo in top left
  # favicon: "_static/favicon.png"
  custom_dir: "_overrides" # Overriding part of the HTML

  # These additions are my own custom ones, having overridden a partial.
  twitter_name: "@avikpal1410"
  twitter_url: "https://twitter.com/avikpal1410"

# TODO(@avik-pal): Setup mkdocs for showing documentation versions
extra:
  version:
    provider: mike

site_name: Lux.jl
site_description: Documentation for Lux.jl
site_author: Avik Pal
site_url: http://lux.csail.mit.edu

repo_url: https://github.com/avik-pal/Lux.jl
repo_name: avik-pal/Lux.jl
edit_uri: "" # No edit button, as some of our pages are in /docs and some in /examples via symlink, so it's impossible for them all to be accurate

strict: true # Don't allow warnings during the build process

extra_javascript:
  # The below three make MathJax work, see https://squidfunk.github.io/mkdocs-material/reference/mathjax/
  - _static/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/custom.css
  - assets/Documenter.css

markdown_extensions:
  - admonition
  - toc:
      permalink: "Â¤" # Adds a clickable permalink to each section heading
      toc_depth: 4
  - pymdownx.arithmatex: # Render LaTeX via MathJax
      generic: true
  - pymdownx.details # Allowing hidden expandable regions denoted by ???
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences # Seems to enable syntax highlighting when used with the Material theme.
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.tabbed:
      alternate_style: true 
  - attr_list
  - md_in_html


plugins:
  - search # default search plugin; needs manually re-enabling when using any other plugins
  - autorefs # Cross-links to headings
  - include_exclude_files:
      exclude:
        - "_overrides"
  - mknotebooks # Jupyter notebooks

nav:
  - "Lux.jl: Explicitly Parameterized Neural Networks": "index.md"
  - "Introduction":
      - "All about Lux": "introduction/overview.md"
      - "Ecosystem": "introduction/ecosystem.md"
  - "Tutorials":
      - "Home": "examples/examples.md"
      - "Beginner":
          - "Julia & Lux for the Uninitiated": "examples/generated/beginner/Basics/main.md"
          - "Fitting a Polynomial": "examples/generated/beginner/PolynomialFitting/main.md"
          - "Training a Simple LSTM": "examples/generated/beginner/SimpleRNN/main.md"
      - "Intermediate":
          - "MNIST Classification using NeuralODE": "examples/generated/intermediate/NeuralODE/main.md"
          - "Bayesian Neural Network": "examples/generated/intermediate/BayesianNN/main.md"
          - "Training a Hyper Network": "examples/generated/intermediate/HyperNet/main.md"
  - "Manual":
      - "Lux Interface": "manual/interface.md"
      - "Migrating from Flux to Lux": "manual/migrate_from_flux.md"
      - "Freezing Model Parameters": "manual/freezing_parameters.md"
      - "Dispatch on Custom Inputs": "manual/dispatch_custom_inputs.md"
  - "API Reference":
      - "Layers": "api/layers.md"
      - "Functional": "api/functional.md"
      - "Core": "api/core.md"
      - "Utilities": "api/utilities.md"
      - "Flux & Lux InterOp": "api/flux2lux.md"
      - "Experimental": "api/contrib.md"
  - "Frameworks":
      - "Boltz": "lib/Boltz/index.md"
      - "FluxMPI": "https://avik-pal.github.io/FluxMPI.jl/dev/"
      - "NNlib": "https://fluxml.ai/Flux.jl/stable/models/nnlib/"
      - "LuxLib":
        - "Introduction": "lib/LuxLib/index.md"
        - "API Reference": "lib/LuxLib/api.md"
      - "LuxCore":
        - "Introduction": "lib/LuxCore/index.md"
        - "API Reference": "lib/LuxCore/api.md"
  - "Development Documentation":
      - "Style Guide": "devdocs/style_guide.md"
      - "Layer Implementation": "devdocs/layer_implementation.md"
      - "Sub Packages": "devdocs/subpackages.md"
