[deps]
ADTypes = "47edcb42-4c32-4615-8424-f2b9edc5f35b"
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
Enzyme = "7da242da-08ed-463a-9acd-ee780be4f1d9"
FiniteDiff = "6a86dc24-6348-571c-b903-95158fe2bd41"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Functors = "d9f16b24-f501-4c13-a1f2-28368ffc5196"
GPUArraysCore = "46192b85-c4d5-4398-a991-12ede77f4527"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
LuxCore = "bb33d45b-7691-41d6-9220-0943567d0623"
LuxLib = "82251201-b29d-42c6-8e01-566dec8acb11"
LuxTestUtils = "ac9de150-d08f-4546-94fb-7472b5760531"
MLDataDevices = "7e8f7934-dd98-4c1a-8fe8-92b47a384d40"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
NNlib = "872c559c-99b0-510c-b3b7-b6c96a88d5cd"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reactant = "3c362404-f566-11ee-1572-e11a4b42c853"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
WeightInitializers = "d49dbf32-c5c2-4618-8acc-27bb2598ef2d"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[sources]
Lux = {path = "../"}
LuxCore = {path = "../lib/LuxCore"}
LuxLib = {path = "../lib/LuxLib"}
LuxTestUtils = {path = "../lib/LuxTestUtils"}
MLDataDevices = {path = "../lib/MLDataDevices"}
WeightInitializers = {path = "../lib/WeightInitializers"}

[compat]
ADTypes = "1.10"
Adapt = "4"
ChainRulesCore = "1.25.1"
ComponentArrays = "0.15.22"
Documenter = "1.4"
DocumenterCitations = "1.3.6"
DocumenterVitepress = "0.2"
Enzyme = "0.13.81"
FiniteDiff = "2.23.1"
Flux = "0.16.3"
ForwardDiff = "0.10.36, 1"
Functors = "0.5"
GPUArraysCore = "0.2"
KernelAbstractions = "0.9"
LinearAlgebra = "1.10"
Literate = "2.18.0"
Lux = "1"
LuxCore = "1.5"
LuxLib = "1.15"
LuxTestUtils = "2"
MLDataDevices = "1.17"
MLUtils = "0.4.8"
NNlib = "0.9.27"
NPZ = "0.4.3"
Optimisers = "0.4.6"
Printf = "1.10"
Random = "1.10"
Reactant = "0.2.173"
StableRNGs = "1"
StaticArrays = "1"
WeightInitializers = "1.3"
Zygote = "0.7"
julia = "1.10"
