[deps]
JuliaSyntax = "70703baa-626e-46a2-a12c-08ffd08c73b4"
Lux = "aafdbc67-5cd5-409a-82a0-ebc47ac8091e"
ModuleInfo = "3c3ff5e7-c68c-4a09-80d1-9526a1e9878a"
Pollen = "c88717ad-5130-4874-a664-5a9aba5ec443"
